allowBuilds:
  '@sentry/cli': false
  sharp: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - tar@7.5.7
  - tar@7.5.3
  - tar@7.5.8
  - rollup@2.80.0
  - tar@7.5.10
  - tar@7.5.11
  - tar@7.5.4
  - next@16.2.3
  - postcss@8.5.10
  - next@16.2.5
  - next@16.2.6
  - uuid@11.1.1
  - tar@7.5.16
  - sigstore@4.1.1
